services:
  frontend:
    image: interview-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9527:9527"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    image: interview-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge