serverAddr = "xxx"
serverPort = 7000

[common]
token = "your_token"

[frontend]
type = "tcp"
localIP = "127.0.0.1"
localPort = 9527
remotePort = 9527

[backend]
type = "tcp"
localIP = "127.0.0.1"
localPort = 6666
remotePort = 666